#!/bin/bash
# run this after turning on the dsps 

# the following looks at the host variable and sets the ethernet interfact
# appropriately.  Modify this for your system.
eth=eth1

#reload the sysctl settings
# sysctl -p

sysctl -w net.core.rmem_max=8388607
sysctl -w net.core.rmem_default=8388607
sysctl -w net.core.wmem_max=8388607
sysctl -w net.core.wmem_default=8388607
# sysctl -w net.ipv4.neigh.eth0.mcast_solicit=0
# sysctl -w net.ipv4.neigh.eth0.ucast_solicit=1
# sysctl -w net.ipv4.conf.default.forwarding=0

arping -c 1 -I $eth 10.1.2.10 
arping -c 1 -I $eth 10.1.2.11 
arping -c 1 -I $eth 10.1.2.12 
arping -c 1 -I $eth 10.1.2.13 
arping -c 1 -I $eth 10.1.2.14 
arping -c 1 -I $eth 10.1.2.15 
arping -c 1 -I $eth 10.1.2.16 
arping -c 1 -I $eth 10.1.2.17 
arping -c 1 -I $eth 10.1.2.18 
arping -c 1 -I $eth 10.1.2.100

arp | grep dsp | grep -v fakedsp | awk '{print $1 "     " $3}' > /etc/ethers.dsp
arp -f /etc/ethers.dsp

if [ ! -e /dev/video ]; then
  echo "Creating /dev/video soft link."
  ln -s /dev/video0 /dev/video
fi
